### ISSUE TITLE
Regression: Revolut crashes on launch with ZygiskNext

### ISSUE THREAD

**Issue by devnoname120** [Dr-TSNG/ZygiskOnKernelSU#110]
Revolut crashes on launch when ZygiskNext is enabled but works normally with original Zygisk.

# Crash

```
FATAL EXCEPTION: main
Process: com.revolut.revolut, PID: 5154
java.lang.RuntimeException: Unable to create application com.revolut.ProtectedRevolutApplication: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyNDA0MTYtMjAyNDA1MDExNzU1IGI3OmI3IDM0IFhpYW9taS90b2NvX2dsb2JhbC90b2NvOjEyL1JLUTEuMjEwNjE0LjAwMi9WMTMuMC40LjAuU0ZOTUlYTTp1c2VyL3JlbGVhc2Uta2V5cyBibG9ja2VkXQ: DP: 759
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7062)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyNDA0MTYtMjAyNDA1MDExNzU1IGI3OmI3IDM0IFhpYW9taS90b2NvX2dsb2JhbC90b2NvOjEyL1JLUTEuMjEwNjE0LjAwMi9WMTMuMC40LjAuU0ZOTUlYTTp1c2VyL3JlbGVhc2Uta2V5cyBibG9ja2VkXQ: DP: 759
	at com.revolut.ProtectedRevolutApplication.wsJoyeFqz(Unknown Source:5)
	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:46)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1319)
	at java.lang.reflect.Method.invoke(Native Method)
	at dac.cdVDpB.h.Wkq.QDjq.ImKcVYN.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:194)
	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7057)
	... 9 more
Caused by: java.lang.RuntimeException: DP: 759
	at com.revolut.ProtectedRevolutApplication.slcDnGbD(Native Method)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.revolut.ProtectedRevolutApplication$RevolutApplication$a.kfEkeuls(Unknown Source:31)
	at com.revolut.ProtectedRevolutApplication$RevolutApplication$a.nuEBcwACC(Unknown Source:472)
	at com.revolut.ProtectedRevolutApplication.slcDnGbD(Native Method)
	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:41)
	... 15 more
```

# How to reproduce

- Install Revolut.
- Install Magisk Alpha.
- Enable Zygisk.
- Restart.
- Add Revolut to the denylist.
- Enforce the denylist.
- Open Revolut, and confirm that it works.

This confirms that it works without any issues with original Zygisk.

Next steps:
- Disable Zygisk.
- Install ZygiskNext.
- Reboot.
- Open Revolut, it crashes on launch.

**Things I've tried**:
- Remove Revolut from the denylist.
- Disable the denylist.
- Install Shamiko.

**Comment by JasonKhew96** [comment]
this app detect zygisknext, zygisknext does not do hiding itself

**Comment by 5ec1cff** [comment]
![image](https://github.com/Dr-TSNG/ZygiskNext/assets/56485584/d6b96dd8-55c2-4365-9bba-a68a9aa79ec6)

**Comment by devnoname120** [comment]
@5ec1cff Can you try with Shamiko v1.0.1?
